"""
Seed Realistic Prototype Demo Data for HAZARDSHIELD AI
"""

from app.database import SessionLocal, engine, Base
from app.models.habitation import Habitation
from app.models.hazard import Hazard
from app.models.red_zone import RedZone
from app.models.capacity import CarryingCapacity
from app.models.safe_haven import SafeHaven

def seed_db(force: bool = False):
    db = SessionLocal()
    try:
        existing_hab_count = db.query(Habitation).count()
        if existing_hab_count >= 30 and not force:
            return

        db.query(Hazard).delete()
        db.query(Habitation).delete()
        db.query(RedZone).delete()
        db.query(CarryingCapacity).delete()
        db.query(SafeHaven).delete()
        db.commit()

        habitations_data = [
            # Assam
            dict(name="Majuli River Island - Garamur", district="Majuli", state="Assam",
                 latitude=26.95, longitude=94.15, population=8200, families=1822,
                 risk_score=92.4, risk_level="CRITICAL", vulnerability_score=88.5, relocation_priority="IMMEDIATE"),
            dict(name="Salmora Pottery Habitation", district="Majuli", state="Assam",
                 latitude=26.85, longitude=94.22, population=4500, families=980,
                 risk_score=89.0, risk_level="CRITICAL", vulnerability_score=86.0, relocation_priority="IMMEDIATE"),
            dict(name="Dhubri Embankment Cluster", district="Dhubri", state="Assam",
                 latitude=26.02, longitude=89.98, population=11500, families=2550,
                 risk_score=84.5, risk_level="CRITICAL", vulnerability_score=81.0, relocation_priority="IMMEDIATE"),
            dict(name="Dhemaji Lowland Basti", district="Dhemaji", state="Assam",
                 latitude=27.48, longitude=94.58, population=5300, families=1150,
                 risk_score=78.2, risk_level="HIGH", vulnerability_score=74.5, relocation_priority="SHORT_TERM"),
            dict(name="Silchar Barak Valley Basti", district="Cachar", state="Assam",
                 latitude=24.83, longitude=92.78, population=7400, families=1640,
                 risk_score=76.8, risk_level="HIGH", vulnerability_score=73.0, relocation_priority="SHORT_TERM"),

            # Uttarakhand
            dict(name="Devipur Hillside Hamlet", district="Chamoli", state="Uttarakhand",
                 latitude=30.42, longitude=79.58, population=3400, families=756,
                 risk_score=85.2, risk_level="CRITICAL", vulnerability_score=82.0, relocation_priority="IMMEDIATE"),
            dict(name="Joshimath Sinking Sector", district="Chamoli", state="Uttarakhand",
                 latitude=30.55, longitude=79.57, population=6200, families=1380,
                 risk_score=94.0, risk_level="CRITICAL", vulnerability_score=91.5, relocation_priority="IMMEDIATE"),
            dict(name="Dharasu River Bend Hamlet", district="Uttarkashi", state="Uttarakhand",
                 latitude=30.63, longitude=78.32, population=2800, families=620,
                 risk_score=77.5, risk_level="HIGH", vulnerability_score=72.0, relocation_priority="SHORT_TERM"),
            dict(name="Rudraprayag Confluence Settlement", district="Rudraprayag", state="Uttarakhand",
                 latitude=30.28, longitude=78.98, population=4100, families=910,
                 risk_score=75.0, risk_level="HIGH", vulnerability_score=71.0, relocation_priority="SHORT_TERM"),
            dict(name="Pithoragarh Goriganga Slopes", district="Pithoragarh", state="Uttarakhand",
                 latitude=29.58, longitude=80.22, population=2200, families=490,
                 risk_score=68.5, risk_level="HIGH", vulnerability_score=64.0, relocation_priority="MEDIUM_TERM"),

            # Himachal Pradesh
            dict(name="Kinnaur Alpine Gorge", district="Kinnaur", state="Himachal Pradesh",
                 latitude=31.55, longitude=78.27, population=1800, families=400,
                 risk_score=68.9, risk_level="HIGH", vulnerability_score=65.4, relocation_priority="MEDIUM_TERM"),
            dict(name="Kullu Beas Floodplain", district="Kullu", state="Himachal Pradesh",
                 latitude=31.96, longitude=77.11, population=5100, families=1130,
                 risk_score=79.0, risk_level="HIGH", vulnerability_score=75.2, relocation_priority="SHORT_TERM"),
            dict(name="Mandi Suketi Ravine", district="Mandi", state="Himachal Pradesh",
                 latitude=31.71, longitude=76.93, population=3900, families=860,
                 risk_score=73.5, risk_level="HIGH", vulnerability_score=69.0, relocation_priority="SHORT_TERM"),
            dict(name="Lahaul Glacier Outwash Zone", district="Lahaul Spiti", state="Himachal Pradesh",
                 latitude=32.50, longitude=77.60, population=1200, families=260,
                 risk_score=62.0, risk_level="MODERATE", vulnerability_score=58.0, relocation_priority="MEDIUM_TERM"),

            # Odisha
            dict(name="Brahmapur Coast Line Basti", district="Ganjam", state="Odisha",
                 latitude=19.31, longitude=84.79, population=6800, families=1511,
                 risk_score=71.3, risk_level="HIGH", vulnerability_score=68.2, relocation_priority="SHORT_TERM"),
            dict(name="Balasore Sea-Dyke Settlement", district="Balasore", state="Odisha",
                 latitude=21.49, longitude=86.93, population=4800, families=1067,
                 risk_score=72.0, risk_level="HIGH", vulnerability_score=68.0, relocation_priority="SHORT_TERM"),
            dict(name="Kendrapara Tidal Lowland", district="Kendrapara", state="Odisha",
                 latitude=20.50, longitude=86.42, population=8900, families=1980,
                 risk_score=86.5, risk_level="CRITICAL", vulnerability_score=83.0, relocation_priority="IMMEDIATE"),
            dict(name="Puri Coastal Sand Dunes", district="Puri", state="Odisha",
                 latitude=19.81, longitude=85.83, population=9200, families=2050,
                 risk_score=65.0, risk_level="MODERATE", vulnerability_score=60.0, relocation_priority="MEDIUM_TERM"),

            # West Bengal
            dict(name="Sunderbans Delta - Gosaba", district="South 24 Parganas", state="West Bengal",
                 latitude=21.95, longitude=88.90, population=9400, families=2089,
                 risk_score=88.7, risk_level="CRITICAL", vulnerability_score=85.0, relocation_priority="IMMEDIATE"),
            dict(name="Mousuni Island Fisher Village", district="South 24 Parganas", state="West Bengal",
                 latitude=21.65, longitude=88.25, population=5200, families=1150,
                 risk_score=89.5, risk_level="CRITICAL", vulnerability_score=87.0, relocation_priority="IMMEDIATE"),
            dict(name="Digha Sea Front Habitation", district="Purba Medinipur", state="West Bengal",
                 latitude=21.62, longitude=87.50, population=6400, families=1420,
                 risk_score=70.0, risk_level="HIGH", vulnerability_score=66.5, relocation_priority="SHORT_TERM"),

            # Bihar
            dict(name="Darbhanga Flood Plains", district="Darbhanga", state="Bihar",
                 latitude=26.15, longitude=85.90, population=5600, families=1244,
                 risk_score=85.0, risk_level="CRITICAL", vulnerability_score=81.5, relocation_priority="IMMEDIATE"),
            dict(name="Supaul Kosi Embankment Ring", district="Supaul", state="Bihar",
                 latitude=26.50, longitude=86.60, population=12000, families=2650,
                 risk_score=91.0, risk_level="CRITICAL", vulnerability_score=89.0, relocation_priority="IMMEDIATE"),
            dict(name="Katihar River Junction Tola", district="Katihar", state="Bihar",
                 latitude=25.54, longitude=87.57, population=7800, families=1730,
                 risk_score=81.5, risk_level="CRITICAL", vulnerability_score=78.0, relocation_priority="IMMEDIATE"),
            dict(name="Samastipur Budhi Gandak Basin", district="Samastipur", state="Bihar",
                 latitude=25.86, longitude=85.78, population=6100, families=1350,
                 risk_score=69.0, risk_level="HIGH", vulnerability_score=64.0, relocation_priority="SHORT_TERM"),

            # Kerala
            dict(name="Munnar Highland Valley", district="Idukki", state="Kerala",
                 latitude=10.09, longitude=77.06, population=2100, families=467,
                 risk_score=74.1, risk_level="HIGH", vulnerability_score=70.8, relocation_priority="SHORT_TERM"),
            dict(name="Wayanad Meppadi Hillside", district="Wayanad", state="Kerala",
                 latitude=11.61, longitude=76.08, population=3800, families=840,
                 risk_score=88.0, risk_level="CRITICAL", vulnerability_score=84.5, relocation_priority="IMMEDIATE"),
            dict(name="Alappuzha Kuttanad Waterway", district="Alappuzha", state="Kerala",
                 latitude=9.49, longitude=76.33, population=8100, families=1800,
                 risk_score=77.0, risk_level="HIGH", vulnerability_score=74.0, relocation_priority="SHORT_TERM"),

            # Andhra Pradesh
            dict(name="Krishna Nagar Delta Coast", district="Krishna", state="Andhra Pradesh",
                 latitude=16.18, longitude=80.95, population=5600, families=1244,
                 risk_score=78.6, risk_level="HIGH", vulnerability_score=74.3, relocation_priority="SHORT_TERM"),
            dict(name="Diviseema Cyclone Front", district="Krishna", state="Andhra Pradesh",
                 latitude=15.95, longitude=80.90, population=4900, families=1090,
                 risk_score=76.0, risk_level="HIGH", vulnerability_score=72.0, relocation_priority="SHORT_TERM"),

            # Maharashtra
            dict(name="Chiplun Riverbed Settlement", district="Ratnagiri", state="Maharashtra",
                 latitude=17.53, longitude=73.52, population=4200, families=933,
                 risk_score=62.5, risk_level="MODERATE", vulnerability_score=59.8, relocation_priority="MEDIUM_TERM"),
            dict(name="Mahad Savitri Basin", district="Raigad", state="Maharashtra",
                 latitude=18.08, longitude=73.42, population=5300, families=1170,
                 risk_score=64.0, risk_level="MODERATE", vulnerability_score=60.0, relocation_priority="MEDIUM_TERM"),
        ]

        hab_objs = []
        for h in habitations_data:
            obj = Habitation(**h)
            db.add(obj)
            hab_objs.append(obj)
        db.flush()

        hazards_data = [
            dict(habitation_id=hab_objs[0].id, hazard_type="Flood", hazard_score=95.0, severity="CRITICAL",
                 description="Severe seasonal riverbank inundation from Brahmaputra flood wave"),
            dict(habitation_id=hab_objs[0].id, hazard_type="Coastal Erosion", hazard_score=90.0, severity="CRITICAL",
                 description="Active erosion of island soil cutting habitation foundation"),
            dict(habitation_id=hab_objs[1].id, hazard_type="Flood", hazard_score=88.0, severity="CRITICAL",
                 description="Annual siltation and deep flood water overflow"),
            dict(habitation_id=hab_objs[2].id, hazard_type="Flood", hazard_score=85.0, severity="CRITICAL",
                 description="Dhubri international river border flood surge"),
            dict(habitation_id=hab_objs[3].id, hazard_type="Extreme Rainfall", hazard_score=79.0, severity="HIGH",
                 description="Flash deluge from Arunachal foothills downflow"),
            dict(habitation_id=hab_objs[5].id, hazard_type="Landslide", hazard_score=88.0, severity="CRITICAL",
                 description="Steep slope debris flow during heavy monsoon"),
            dict(habitation_id=hab_objs[6].id, hazard_type="Landslide", hazard_score=95.0, severity="CRITICAL",
                 description="Severe land subsidence and structural foundation fissures"),
            dict(habitation_id=hab_objs[6].id, hazard_type="Cloudburst", hazard_score=85.0, severity="HIGH",
                 description="Intense localized precipitation over Himalayan crest"),
            dict(habitation_id=hab_objs[7].id, hazard_type="Landslide", hazard_score=78.0, severity="HIGH",
                 description="Bhagirathi river gorge toe-cutting inducing rockfall"),
            dict(habitation_id=hab_objs[10].id, hazard_type="Landslide", hazard_score=72.0, severity="HIGH",
                 description="High seismic faultline active rockfall zone"),
            dict(habitation_id=hab_objs[11].id, hazard_type="Extreme Rainfall", hazard_score=80.0, severity="HIGH",
                 description="Beas river swelling with torrential mountain rain"),
            dict(habitation_id=hab_objs[14].id, hazard_type="Cyclone", hazard_score=73.0, severity="HIGH",
                 description="Direct Bay of Bengal deep depression landfall vector"),
            dict(habitation_id=hab_objs[15].id, hazard_type="Cyclone", hazard_score=74.0, severity="HIGH",
                 description="Gale-force coastal wind speeds with sea ingress"),
            dict(habitation_id=hab_objs[16].id, hazard_type="Cyclone", hazard_score=89.0, severity="CRITICAL",
                 description="Catastrophic storm surge breach across delta embankments"),
            dict(habitation_id=hab_objs[18].id, hazard_type="Flood", hazard_score=90.0, severity="CRITICAL",
                 description="Saline tidal surge breaching delta dykes during cyclones"),
            dict(habitation_id=hab_objs[19].id, hazard_type="Coastal Erosion", hazard_score=92.0, severity="CRITICAL",
                 description="High sea level rise leading to rapid island area reduction"),
            dict(habitation_id=hab_objs[21].id, hazard_type="Flood", hazard_score=87.0, severity="CRITICAL",
                 description="Kamla Balan river sudden embankment overflow"),
            dict(habitation_id=hab_objs[22].id, hazard_type="Flood", hazard_score=94.0, severity="CRITICAL",
                 description="Kosi river shifting course causing massive seasonal deluges"),
            dict(habitation_id=hab_objs[23].id, hazard_type="Flood", hazard_score=82.0, severity="CRITICAL",
                 description="Mahananda river flood wave inundation"),
            dict(habitation_id=hab_objs[25].id, hazard_type="Landslide", hazard_score=76.0, severity="HIGH",
                 description="Steep Western Ghats tea garden slope failure"),
            dict(habitation_id=hab_objs[26].id, hazard_type="Landslide", hazard_score=92.0, severity="CRITICAL",
                 description="Catastrophic debris avalanche and mudslide runout"),
            dict(habitation_id=hab_objs[27].id, hazard_type="Flood", hazard_score=78.0, severity="HIGH",
                 description="Sub-sea level agricultural polder flooding in Kuttanad"),
            dict(habitation_id=hab_objs[28].id, hazard_type="Cyclone", hazard_score=80.0, severity="HIGH",
                 description="Krishna river delta cyclone storm surge risk"),
            dict(habitation_id=hab_objs[30].id, hazard_type="Extreme Rainfall", hazard_score=65.0, severity="MODERATE",
                 description="Vashishti river flash overflow during concentrated rainfall"),
        ]
        for hz in hazards_data:
            db.add(Hazard(**hz))

        red_zones_data = [
            dict(name="Majuli Brahmaputra River Basin", state="Assam", district="Majuli",
                 latitude=26.95, longitude=94.15, radius=14.0, risk_score=94.0,
                 risk_level="CRITICAL", hazard_type="Flood", population=12700, status="ACTIVE"),
            dict(name="Joshimath Subsidence Red Perimeter", state="Uttarakhand", district="Chamoli",
                 latitude=30.55, longitude=79.57, radius=6.5, risk_score=95.0,
                 risk_level="CRITICAL", hazard_type="Landslide", population=6200, status="ACTIVE"),
            dict(name="Devipur Landslide Buffer", state="Uttarakhand", district="Chamoli",
                 latitude=30.42, longitude=79.58, radius=8.0, risk_score=88.0,
                 risk_level="CRITICAL", hazard_type="Landslide", population=3400, status="ACTIVE"),
            dict(name="Wayanad Meppadi Debris Flow Zone", state="Kerala", district="Wayanad",
                 latitude=11.61, longitude=76.08, radius=7.5, risk_score=91.0,
                 risk_level="CRITICAL", hazard_type="Landslide", population=3800, status="ACTIVE"),
            dict(name="Sunderbans Gosaba Delta Inundation Sector", state="West Bengal", district="South 24 Parganas",
                 latitude=21.95, longitude=88.90, radius=16.0, risk_score=90.0,
                 risk_level="CRITICAL", hazard_type="Cyclone", population=14600, status="ACTIVE"),
            dict(name="Mousuni Island Erosion Front", state="West Bengal", district="South 24 Parganas",
                 latitude=21.65, longitude=88.25, radius=9.0, risk_score=91.5,
                 risk_level="CRITICAL", hazard_type="Coastal Erosion", population=5200, status="ACTIVE"),
            dict(name="Supaul Kosi River High Vulnerability Zone", state="Bihar", district="Supaul",
                 latitude=26.50, longitude=86.60, radius=18.0, risk_score=92.0,
                 risk_level="CRITICAL", hazard_type="Flood", population=18000, status="ACTIVE"),
            dict(name="Darbhanga Flood Corridor", state="Bihar", district="Darbhanga",
                 latitude=26.15, longitude=85.90, radius=12.0, risk_score=86.0,
                 risk_level="CRITICAL", hazard_type="Flood", population=8500, status="ACTIVE"),
            dict(name="Katihar Confluence Flood Zone", state="Bihar", district="Katihar",
                 latitude=25.54, longitude=87.57, radius=11.0, risk_score=83.0,
                 risk_level="CRITICAL", hazard_type="Flood", population=9800, status="ACTIVE"),
            dict(name="Kendrapara Coastal Surge Belt", state="Odisha", district="Kendrapara",
                 latitude=20.50, longitude=86.42, radius=15.0, risk_score=87.0,
                 risk_level="CRITICAL", hazard_type="Cyclone", population=11500, status="ACTIVE"),
            dict(name="Dhubri International River Belt", state="Assam", district="Dhubri",
                 latitude=26.02, longitude=89.98, radius=20.0, risk_score=85.0,
                 risk_level="CRITICAL", hazard_type="Flood", population=15000, status="ACTIVE"),
            dict(name="Balasore Cyclone Coast Sector", state="Odisha", district="Balasore",
                 latitude=21.49, longitude=86.93, radius=10.0, risk_score=75.0,
                 risk_level="HIGH", hazard_type="Cyclone", population=6500, status="ACTIVE"),
            dict(name="Ganjam Coastal Surge Area", state="Odisha", district="Ganjam",
                 latitude=19.31, longitude=84.79, radius=8.5, risk_score=73.0,
                 risk_level="HIGH", hazard_type="Cyclone", population=7200, status="ACTIVE"),
            dict(name="Kinnaur Rockfall Hazard Sector", state="Himachal Pradesh", district="Kinnaur",
                 latitude=31.55, longitude=78.27, radius=6.0, risk_score=71.0,
                 risk_level="HIGH", hazard_type="Landslide", population=2200, status="ACTIVE"),
            dict(name="Kullu Beas Valley Flash Zone", state="Himachal Pradesh", district="Kullu",
                 latitude=31.96, longitude=77.11, radius=9.5, risk_score=78.0,
                 risk_level="HIGH", hazard_type="Extreme Rainfall", population=6000, status="ACTIVE"),
            dict(name="Idukki Slope Failure Perimeter", state="Kerala", district="Idukki",
                 latitude=10.09, longitude=77.06, radius=6.5, risk_score=76.0,
                 risk_level="HIGH", hazard_type="Landslide", population=2800, status="ACTIVE"),
            dict(name="Alappuzha Kuttanad Inundation Belt", state="Kerala", district="Alappuzha",
                 latitude=9.49, longitude=76.33, radius=10.0, risk_score=77.0,
                 risk_level="HIGH", hazard_type="Flood", population=9500, status="ACTIVE"),
            dict(name="Krishna Delta Cyclone Sector", state="Andhra Pradesh", district="Krishna",
                 latitude=16.18, longitude=80.95, radius=10.5, risk_score=78.5,
                 risk_level="HIGH", hazard_type="Cyclone", population=7500, status="ACTIVE"),
            dict(name="Uttarkashi Bhagirathi Slope Belt", state="Uttarakhand", district="Uttarkashi",
                 latitude=30.63, longitude=78.32, radius=8.0, risk_score=76.0,
                 risk_level="HIGH", hazard_type="Landslide", population=3900, status="MONITORING"),
            dict(name="Digha Sea Front Risk Strip", state="West Bengal", district="Purba Medinipur",
                 latitude=21.62, longitude=87.50, radius=7.0, risk_score=69.0,
                 risk_level="HIGH", hazard_type="Coastal Erosion", population=7000, status="MONITORING"),
            dict(name="Chiplun Vashishti Flood Belt", state="Maharashtra", district="Ratnagiri",
                 latitude=17.53, longitude=73.52, radius=6.0, risk_score=64.0,
                 risk_level="MODERATE", hazard_type="Extreme Rainfall", population=4900, status="MONITORING"),
            dict(name="Mahad Savitri River Risk Zone", state="Maharashtra", district="Raigad",
                 latitude=18.08, longitude=73.42, radius=6.5, risk_score=63.0,
                 risk_level="MODERATE", hazard_type="Flood", population=5800, status="RESOLVED"),
        ]
        for rz in red_zones_data:
            db.add(RedZone(**rz))

        capacity_data = [
            dict(location_name="Majuli Relief & Transit Camp", state="Assam", district="Majuli",
                 latitude=26.88, longitude=94.05, total_capacity=6000, occupied_capacity=5700,
                 available_capacity=300, housing_capacity=2000, water_capacity=8000,
                 healthcare_capacity=500, shelter_capacity=6000, capacity_score=95.0, status="CRITICAL"),
            dict(location_name="Devipur SDMA Emergency Camp", state="Uttarakhand", district="Chamoli",
                 latitude=30.35, longitude=79.50, total_capacity=2500, occupied_capacity=2380,
                 available_capacity=120, housing_capacity=800, water_capacity=3000,
                 healthcare_capacity=200, shelter_capacity=2500, capacity_score=95.2, status="CRITICAL"),
            dict(location_name="Joshimath Rehabilitation Hub", state="Uttarakhand", district="Chamoli",
                 latitude=30.52, longitude=79.60, total_capacity=3000, occupied_capacity=2950,
                 available_capacity=50, housing_capacity=1000, water_capacity=3500,
                 healthcare_capacity=250, shelter_capacity=3000, capacity_score=98.3, status="CRITICAL"),
            dict(location_name="Sunderbans Transit Hub - Kakdwip", state="West Bengal", district="South 24 Parganas",
                 latitude=22.05, longitude=88.85, total_capacity=7000, occupied_capacity=6650,
                 available_capacity=350, housing_capacity=2500, water_capacity=9000,
                 healthcare_capacity=600, shelter_capacity=7000, capacity_score=95.0, status="CRITICAL"),
            dict(location_name="Bihar Kosi Relief Centre - Supaul", state="Bihar", district="Supaul",
                 latitude=26.48, longitude=86.55, total_capacity=9000, occupied_capacity=8600,
                 available_capacity=400, housing_capacity=3200, water_capacity=11000,
                 healthcare_capacity=750, shelter_capacity=9000, capacity_score=95.5, status="CRITICAL"),
            dict(location_name="Darbhanga Central Relief Center", state="Bihar", district="Darbhanga",
                 latitude=26.10, longitude=85.80, total_capacity=8000, occupied_capacity=7400,
                 available_capacity=600, housing_capacity=3000, water_capacity=10000,
                 healthcare_capacity=700, shelter_capacity=8000, capacity_score=92.5, status="CRITICAL"),
            dict(location_name="Wayanad Meppadi Disaster Shelter", state="Kerala", district="Wayanad",
                 latitude=11.55, longitude=76.00, total_capacity=3500, occupied_capacity=3200,
                 available_capacity=300, housing_capacity=1200, water_capacity=4000,
                 healthcare_capacity=300, shelter_capacity=3500, capacity_score=91.4, status="CRITICAL"),
            dict(location_name="Ganjam Coastal Shelter Zone", state="Odisha", district="Ganjam",
                 latitude=19.25, longitude=84.70, total_capacity=5000, occupied_capacity=3500,
                 available_capacity=1500, housing_capacity=1800, water_capacity=6000,
                 healthcare_capacity=400, shelter_capacity=5000, capacity_score=70.0, status="SUFFICIENT"),
            dict(location_name="Balasore Cyclone Multipurpose Shelter", state="Odisha", district="Balasore",
                 latitude=21.45, longitude=86.85, total_capacity=6000, occupied_capacity=4200,
                 available_capacity=1800, housing_capacity=2200, water_capacity=7500,
                 healthcare_capacity=500, shelter_capacity=6000, capacity_score=70.0, status="SUFFICIENT"),
            dict(location_name="Kinnaur Transit & Base Camp", state="Himachal Pradesh", district="Kinnaur",
                 latitude=31.50, longitude=78.20, total_capacity=1500, occupied_capacity=900,
                 available_capacity=600, housing_capacity=500, water_capacity=2000,
                 healthcare_capacity=150, shelter_capacity=1500, capacity_score=60.0, status="SUFFICIENT"),
            dict(location_name="Kullu District Emergency Shelter", state="Himachal Pradesh", district="Kullu",
                 latitude=31.90, longitude=77.15, total_capacity=3500, occupied_capacity=2800,
                 available_capacity=700, housing_capacity=1400, water_capacity=4500,
                 healthcare_capacity=300, shelter_capacity=3500, capacity_score=80.0, status="NEAR_LIMIT"),
            dict(location_name="Dhubri Embankment Shelter Cluster", state="Assam", district="Dhubri",
                 latitude=26.05, longitude=90.02, total_capacity=8500, occupied_capacity=7650,
                 available_capacity=850, housing_capacity=3000, water_capacity=10000,
                 healthcare_capacity=650, shelter_capacity=8500, capacity_score=90.0, status="CRITICAL"),
            dict(location_name="Krishna Delta Transit Station", state="Andhra Pradesh", district="Krishna",
                 latitude=16.22, longitude=80.88, total_capacity=4500, occupied_capacity=3150,
                 available_capacity=1350, housing_capacity=1600, water_capacity=5500,
                 healthcare_capacity=350, shelter_capacity=4500, capacity_score=70.0, status="SUFFICIENT"),
            dict(location_name="Alappuzha Flood Relief Camp", state="Kerala", district="Alappuzha",
                 latitude=9.52, longitude=76.38, total_capacity=5500, occupied_capacity=4400,
                 available_capacity=1100, housing_capacity=2000, water_capacity=6500,
                 healthcare_capacity=450, shelter_capacity=5500, capacity_score=80.0, status="NEAR_LIMIT"),
            dict(location_name="Ratnagiri Regional Shelter Facility", state="Maharashtra", district="Ratnagiri",
                 latitude=17.48, longitude=73.45, total_capacity=4000, occupied_capacity=2200,
                 available_capacity=1800, housing_capacity=1500, water_capacity=5000,
                 healthcare_capacity=350, shelter_capacity=4000, capacity_score=55.0, status="SUFFICIENT"),
            dict(location_name="Mahad Emergency Relief Camp", state="Maharashtra", district="Raigad",
                 latitude=18.12, longitude=73.48, total_capacity=3500, occupied_capacity=1900,
                 available_capacity=1600, housing_capacity=1300, water_capacity=4200,
                 healthcare_capacity=300, shelter_capacity=3500, capacity_score=54.2, status="SUFFICIENT"),
        ]
        for c in capacity_data:
            db.add(CarryingCapacity(**c))

        safe_havens_data = [
            dict(name="Safe Haven Alpha - Sivasagar Complex", district="Sivasagar", state="Assam",
                 latitude=26.99, longitude=94.79, total_capacity=6000, occupied_capacity=1200,
                 available_capacity=4800, safety_score=92.0, road_access_score=88.0,
                 healthcare_score=86.0, suitability_score=90.0, status="AVAILABLE"),
            dict(name="Safe Haven Beta - Dehradun Regional Hub", district="Dehradun", state="Uttarakhand",
                 latitude=30.32, longitude=78.03, total_capacity=9000, occupied_capacity=2500,
                 available_capacity=6500, safety_score=94.0, road_access_score=95.0,
                 healthcare_score=93.0, suitability_score=94.2, status="AVAILABLE"),
            dict(name="Safe Haven Gamma - Bhubaneswar SDMA Complex", district="Khordha", state="Odisha",
                 latitude=20.30, longitude=85.82, total_capacity=7500, occupied_capacity=1800,
                 available_capacity=5700, safety_score=90.0, road_access_score=92.0,
                 healthcare_score=91.0, suitability_score=91.5, status="AVAILABLE"),
            dict(name="Safe Haven Delta - Diamond Harbour Facility", district="South 24 Parganas", state="West Bengal",
                 latitude=22.19, longitude=88.19, total_capacity=5000, occupied_capacity=1100,
                 available_capacity=3900, safety_score=85.0, road_access_score=84.0,
                 healthcare_score=82.0, suitability_score=84.5, status="AVAILABLE"),
            dict(name="Safe Haven Epsilon - Patna Mega Evacuation Zone", district="Patna", state="Bihar",
                 latitude=25.59, longitude=85.14, total_capacity=12000, occupied_capacity=3200,
                 available_capacity=8800, safety_score=88.0, road_access_score=92.0,
                 healthcare_score=90.0, suitability_score=90.0, status="AVAILABLE"),
            dict(name="Safe Haven Zeta - Kozhikode Inland Complex", district="Kozhikode", state="Kerala",
                 latitude=11.25, longitude=75.77, total_capacity=6500, occupied_capacity=1600,
                 available_capacity=4900, safety_score=91.0, road_access_score=90.0,
                 healthcare_score=93.0, suitability_score=91.8, status="AVAILABLE"),
            dict(name="Safe Haven Eta - Shimla Sub-Divisional Base", district="Shimla", state="Himachal Pradesh",
                 latitude=31.10, longitude=77.17, total_capacity=4000, occupied_capacity=900,
                 available_capacity=3100, safety_score=89.0, road_access_score=86.0,
                 healthcare_score=88.0, suitability_score=88.2, status="AVAILABLE"),
            dict(name="Safe Haven Theta - Nagpur Strategic Reserve", district="Nagpur", state="Maharashtra",
                 latitude=21.15, longitude=79.09, total_capacity=8500, occupied_capacity=2200,
                 available_capacity=6300, safety_score=88.0, road_access_score=94.0,
                 healthcare_score=90.0, suitability_score=90.5, status="AVAILABLE"),
            dict(name="Safe Haven Iota - Vijayawada Uplands Hub", district="Krishna", state="Andhra Pradesh",
                 latitude=16.52, longitude=80.62, total_capacity=7000, occupied_capacity=1500,
                 available_capacity=5500, safety_score=88.0, road_access_score=92.0,
                 healthcare_score=89.0, suitability_score=89.8, status="AVAILABLE"),
            dict(name="Safe Haven Kappa - Guwahati Mega Hub", district="Kamrup", state="Assam",
                 latitude=26.14, longitude=91.74, total_capacity=15000, occupied_capacity=4200,
                 available_capacity=10800, safety_score=91.0, road_access_score=96.0,
                 healthcare_score=93.0, suitability_score=93.0, status="AVAILABLE"),
            dict(name="Safe Haven Lambda - Rishikesh Transit Center", district="Dehradun", state="Uttarakhand",
                 latitude=30.08, longitude=78.26, total_capacity=4500, occupied_capacity=3800,
                 available_capacity=700, safety_score=87.0, road_access_score=89.0,
                 healthcare_score=85.0, suitability_score=87.0, status="LIMITED"),
            dict(name="Safe Haven Mu - Saharsa Emergency Shelter", district="Saharsa", state="Bihar",
                 latitude=25.88, longitude=86.60, total_capacity=5000, occupied_capacity=4800,
                 available_capacity=200, safety_score=82.0, road_access_score=80.0,
                 healthcare_score=78.0, suitability_score=80.0, status="LIMITED"),
        ]
        for sh in safe_havens_data:
            db.add(SafeHaven(**sh))

        db.commit()
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
    finally:
        db.close()
